name: Build and push egov-mdms-services image

on:
  push:
   # paths:
    #  - 'core-services/**'
    branches:
      - githubaction-test

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 6
    - run: echo $SHA
      env: 
        SHA: ${{ steps.short-sha.outputs.sha }}
    - run: echo $SHA
      env: 
        SHA: ${{ env.SHA }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME_SECRET }}
        password: ${{ secrets.GHCR_PASSWORD_SECRET }} 
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ‘1.13.3’

    - name: Build and push
      run: |
         echo `git diff HEAD~1 | grep 'git' | cut -d " " -f 3 | cut -d "/" -f 3 | uniq -d | sort -nr ` > servicelist
         cat servicelist
         go version
         ls -ll
