name: Build and push core-services images

on:
  push:
    paths:
      - 'core-services/**'
    branches:
      - gitactions_deploy

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
      with:
       fetch-depth: '0'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME_SECRET }}
        password: ${{ secrets.GHCR_PASSWORD_SECRET }} 
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.13.3'

    - name: Build and push
      env:
        COMMIT-SHA: ${{ github.run_id }}-${{ github.run_number }}
      run: |
         chmod +x build_utilities/build_svc.sh
         ./build_utilities/build_svc.sh
         mv build_utilities/build_setup.go .
         go run build_setup.go
    - name: deploy
      uses: egovernments/DIGIT-DevOps

