name: Build and push egov-mdms-services image

on:
  push:
    #paths:
     # - 'core-services/**'
    branches:
      - githubaction-test

jobs:
  build:
    runs-on: 'ubuntu-latest'
    env:
      COMMIT-SHA: "${{ GITHUB_RUN_ID }}-${{ GITHUB_RUN_NUMBER }}"

    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
      with:
       fetch-depth: '0'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME_SECRET }}
        password: ${{ secrets.GHCR_PASSWORD_SECRET }} 
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.13.3'

    - name: Build and push
      run: |
         echo ${{ emv.COMMIT-SHA }}
         echo $COMMIT-SHA
         #chmod +x build_utilities/build_svc.sh
         #./build_utilities/build_svc.sh
         #cd build_utilities/
         #go run build_setup.go
         
